### ISSUE TITLE
FR: Two new fields in the exported files

### ISSUE THREAD

**Issue by hummelstrand** [jstarpl/nightscout-exporter#3]
The "sgv" field is the most interesting field for most users, but it is a bit obscure. If the exported file could get two new fields (immediately to the right of the existing "sgv" field) with the following header/data:

"BG mg/dL" with the same data as the existing "sgv" field.
"BG mmol/L" with the data "sgv/18.018", rounded to 1 decimal.

**Comment by jstarpl** [comment]
I've added the processed variables, so they should now be available.
